/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedCarriersRouteImport } from './routes/_authenticated/carriers'
import { Route as AuthenticatedDirectoryRouteImport } from './routes/_authenticated/directory'
import { Route as AuthenticatedDispatchRouteImport } from './routes/_authenticated/dispatch'
import { Route as AuthenticatedFleetRouteImport } from './routes/_authenticated/fleet'
import { Route as AuthenticatedLeadsRouteImport } from './routes/_authenticated/leads'
import { Route as AuthenticatedQuickbooksRouteImport } from './routes/_authenticated/quickbooks'
import { Route as AuthenticatedQuotesRouteImport } from './routes/_authenticated/quotes'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as OfferTokenRouteImport } from './routes/offer.$token'
import { Route as OnboardTokenRouteImport } from './routes/onboard.$token'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as OauthGoogle_mailReturnRouteImport } from './routes/oauth/google_mail/return'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarriersRoute = AuthenticatedCarriersRouteImport.update({
  id: '/carriers',
  path: '/carriers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDirectoryRoute = AuthenticatedDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDispatchRoute = AuthenticatedDispatchRouteImport.update({
  id: '/dispatch',
  path: '/dispatch',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFleetRoute = AuthenticatedFleetRouteImport.update({
  id: '/fleet',
  path: '/fleet',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeadsRoute = AuthenticatedLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuickbooksRoute = AuthenticatedQuickbooksRouteImport.update({
  id: '/quickbooks',
  path: '/quickbooks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedQuotesRoute = AuthenticatedQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const OfferTokenRoute = OfferTokenRouteImport.update({
  id: '/offer/$token',
  path: '/offer/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardTokenRoute = OnboardTokenRouteImport.update({
  id: '/onboard/$token',
  path: '/onboard/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthGoogle_mailReturnRoute = OauthGoogle_mailReturnRouteImport.update({
  id: '/oauth/google_mail/return',
  path: '/oauth/google_mail/return',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carriers': typeof AuthenticatedCarriersRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/quickbooks': typeof AuthenticatedQuickbooksRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/offer/$token': typeof OfferTokenRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/oauth/google_mail/return': typeof OauthGoogle_mailReturnRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/carriers': typeof AuthenticatedCarriersRoute
  '/directory': typeof AuthenticatedDirectoryRoute
  '/dispatch': typeof AuthenticatedDispatchRoute
  '/fleet': typeof AuthenticatedFleetRoute
  '/leads': typeof AuthenticatedLeadsRoute
  '/quickbooks': typeof AuthenticatedQuickbooksRoute
  '/quotes': typeof AuthenticatedQuotesRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/offer/$token': typeof OfferTokenRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/oauth/google_mail/return': typeof OauthGoogle_mailReturnRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/carriers': typeof AuthenticatedCarriersRoute
  '/_authenticated/directory': typeof AuthenticatedDirectoryRoute
  '/_authenticated/dispatch': typeof AuthenticatedDispatchRoute
  '/_authenticated/fleet': typeof AuthenticatedFleetRoute
  '/_authenticated/leads': typeof AuthenticatedLeadsRoute
  '/_authenticated/quickbooks': typeof AuthenticatedQuickbooksRoute
  '/_authenticated/quotes': typeof AuthenticatedQuotesRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/offer/$token': typeof OfferTokenRoute
  '/onboard/$token': typeof OnboardTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/oauth/google_mail/return': typeof OauthGoogle_mailReturnRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/carriers'
    | '/directory'
    | '/dispatch'
    | '/fleet'
    | '/leads'
    | '/quickbooks'
    | '/quotes'
    | '/reports'
    | '/offer/$token'
    | '/onboard/$token'
    | '/sign/$token'
    | '/oauth/google_mail/return'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin'
    | '/carriers'
    | '/directory'
    | '/dispatch'
    | '/fleet'
    | '/leads'
    | '/quickbooks'
    | '/quotes'
    | '/reports'
    | '/offer/$token'
    | '/onboard/$token'
    | '/sign/$token'
    | '/oauth/google_mail/return'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/carriers'
    | '/_authenticated/directory'
    | '/_authenticated/dispatch'
    | '/_authenticated/fleet'
    | '/_authenticated/leads'
    | '/_authenticated/quickbooks'
    | '/_authenticated/quotes'
    | '/_authenticated/reports'
    | '/offer/$token'
    | '/onboard/$token'
    | '/sign/$token'
    | '/oauth/google_mail/return'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OfferTokenRoute: typeof OfferTokenRoute
  OnboardTokenRoute: typeof OnboardTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  OauthGoogle_mailReturnRoute: typeof OauthGoogle_mailReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carriers': {
      id: '/_authenticated/carriers'
      path: '/carriers'
      fullPath: '/carriers'
      preLoaderRoute: typeof AuthenticatedCarriersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/directory': {
      id: '/_authenticated/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof AuthenticatedDirectoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dispatch': {
      id: '/_authenticated/dispatch'
      path: '/dispatch'
      fullPath: '/dispatch'
      preLoaderRoute: typeof AuthenticatedDispatchRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fleet': {
      id: '/_authenticated/fleet'
      path: '/fleet'
      fullPath: '/fleet'
      preLoaderRoute: typeof AuthenticatedFleetRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leads': {
      id: '/_authenticated/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof AuthenticatedLeadsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quickbooks': {
      id: '/_authenticated/quickbooks'
      path: '/quickbooks'
      fullPath: '/quickbooks'
      preLoaderRoute: typeof AuthenticatedQuickbooksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/quotes': {
      id: '/_authenticated/quotes'
      path: '/quotes'
      fullPath: '/quotes'
      preLoaderRoute: typeof AuthenticatedQuotesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/offer/$token': {
      id: '/offer/$token'
      path: '/offer/$token'
      fullPath: '/offer/$token'
      preLoaderRoute: typeof OfferTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard/$token': {
      id: '/onboard/$token'
      path: '/onboard/$token'
      fullPath: '/onboard/$token'
      preLoaderRoute: typeof OnboardTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/google_mail/return': {
      id: '/oauth/google_mail/return'
      path: '/oauth/google_mail/return'
      fullPath: '/oauth/google_mail/return'
      preLoaderRoute: typeof OauthGoogle_mailReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedCarriersRoute: typeof AuthenticatedCarriersRoute
  AuthenticatedDirectoryRoute: typeof AuthenticatedDirectoryRoute
  AuthenticatedDispatchRoute: typeof AuthenticatedDispatchRoute
  AuthenticatedFleetRoute: typeof AuthenticatedFleetRoute
  AuthenticatedLeadsRoute: typeof AuthenticatedLeadsRoute
  AuthenticatedQuickbooksRoute: typeof AuthenticatedQuickbooksRoute
  AuthenticatedQuotesRoute: typeof AuthenticatedQuotesRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedCarriersRoute: AuthenticatedCarriersRoute,
  AuthenticatedDirectoryRoute: AuthenticatedDirectoryRoute,
  AuthenticatedDispatchRoute: AuthenticatedDispatchRoute,
  AuthenticatedFleetRoute: AuthenticatedFleetRoute,
  AuthenticatedLeadsRoute: AuthenticatedLeadsRoute,
  AuthenticatedQuickbooksRoute: AuthenticatedQuickbooksRoute,
  AuthenticatedQuotesRoute: AuthenticatedQuotesRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OfferTokenRoute: OfferTokenRoute,
  OnboardTokenRoute: OnboardTokenRoute,
  SignTokenRoute: SignTokenRoute,
  OauthGoogle_mailReturnRoute: OauthGoogle_mailReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
